
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vanaofgfopxswjyczgwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbmFvZmdmb3B4c3dqeWN6Z3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzM4NDMsImV4cCI6MjA1OTkwOTg0M30.4-5RJFEDMsfklxIfEh5cxkcJSwImKZ_KdWCGIuj_bNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
